#!/usr/bin/env python3
import argparse
from pathlib import Path
import sys


def parse_satellites(value_list):
    if not value_list:
        return []
    modules = []
    for value in value_list:
        if isinstance(value, str) and "," in value:
            modules.extend([item.strip() for item in value.split(",") if item.strip()])
        else:
            modules.append(value)
    return modules


def resolve_satellite_files(satellite_dir: Path, requested):
    if not requested:
        return []
    if not satellite_dir.exists() or not satellite_dir.is_dir():
        raise FileNotFoundError(f"Satellite directory not found: {satellite_dir}")

    available = sorted([p for p in satellite_dir.iterdir() if p.is_file()])
    mapped = []
    for name in requested:
        candidate = satellite_dir / name
        if candidate.exists() and candidate.is_file():
            mapped.append(candidate)
            continue
        candidate_md = satellite_dir / f"{name}.md"
        if candidate_md.exists() and candidate_md.is_file():
            mapped.append(candidate_md)
            continue
        matches = [p for p in available if p.stem == name]
        if matches:
            mapped.extend(matches)
            continue
        prefix_matches = [p for p in available if p.stem.startswith(name)]
        if prefix_matches:
            if len(prefix_matches) == 1:
                mapped.append(prefix_matches[0])
                continue
            raise FileNotFoundError(
                f"Ambiguous satellite module prefix: {name} matches {[p.name for p in prefix_matches]}"
            )
        raise FileNotFoundError(f"Satellite module not found: {name}")
    return mapped


def collect_files(directory: Path):
    if not directory.exists() or not directory.is_dir():
        raise FileNotFoundError(f"Module directory not found: {directory}")
    return sorted([p for p in directory.iterdir() if p.is_file()])


def write_combined(output_file: Path, core_files, satellite_files):
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with output_file.open("w", encoding="utf-8") as out:
        # Optional separators and headers between sections
        # out.write("# Combined modules\n\n")
        # out.write("This document was generated by scripts/combine_files.py.\n\n")

        # out.write("## Core modules\n\n")
        for path in core_files:
            # out.write(f"### {path.name}\n\n")
            out.write(path.read_text(encoding="utf-8"))
            if not str(path.read_text(encoding="utf-8")).endswith("\n"):
                out.write("\n")
            # out.write("\n---\n\n")

        if satellite_files:
            out.write("## Satellite modules\n\n")
            for path in satellite_files:
                # out.write(f"### {path.name}\n\n")
                out.write(path.read_text(encoding="utf-8"))
                if not str(path.read_text(encoding="utf-8")).endswith("\n"):
                    out.write("\n")
                # out.write("\n---\n\n")


def main():
    parser = argparse.ArgumentParser(
        description="Combine all files in modules/cores into a single Markdown file.")
    parser.add_argument(
        "-o", "--output",
        default="combined.md",
        help="Output Markdown file path. Default is combined.md relative to modules/.")
    parser.add_argument(
        "-s", "--satellites",
        nargs="*",
        help="Satellite module filenames or names to include from modules/satellites.")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    cores_dir = repo_root / "modules" / "core"
    satellites_dir = repo_root / "modules" / "satellite"
    modules_dir = repo_root / "modules"
    output_file = Path(args.output)
    if not output_file.is_absolute():
        output_file = modules_dir / output_file
    try:
        core_files = collect_files(cores_dir)
        print(f"Found {len(core_files)} core module(s) in {cores_dir}")
        satellite_names = parse_satellites(args.satellites)
        print(f"Requested satellite modules: {satellite_names}")
        satellite_files = resolve_satellite_files(satellites_dir, satellite_names)
        write_combined(output_file, core_files, satellite_files)
        print(f"Combined file written to {output_file}")
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    # e.g. python combine_files.py -s sat_01 for satellite module 1
    main()
